language: python
sudo: false

services:
  - docker

python:
  - "3.6"

install: pip install -r requirements.txt
install: pip install -e app
install: pip install -e web

jobs:
  include:
    - stage: tests
      script: pytest app/tests
      script: pytest web/tests
