language: python
sudo: false

python:
  - "3.6"

services:
  - docker

stages:
  - tests

env:
  - COVERALLS_PARALLEL=true DOCKER_IP='127.0.0.1'

install:
  - pip install -r requirements.txt
  - pip install -e app
  - pip install -e web

jobs:
  include:
    - stage: "tests"
      script:
        - pytest app/tests -v --cov=app/app
        - flake8 app/
    -
      script:
        - pytest web/tests -v --cov=web/web
        - flake8 web/

after_success:
  - coveralls

notifications:
  webhooks: https://coveralls.io/webhook
