language: python
sudo: false

python:
  - "3.6"

services:
  - docker

stages:
  - tests

install:
  - pip install -r requirements.txt
  - pip install -e app/tests
  - pip install -e web/tests

jobs:
  include:
    - stage: "tests"
      script: pytest app/tests
      cript: pytest web/tests
