language: python
sudo: false

services:
  - docker

python:
  - "3.6"

install: 
  - pip install -r requirements.txt
  - pip install -e app

script: pytest app/tests

install: pip install -r requirements.txt
         - pip install -e web

script: pytest web/tests

jobs:
  include:
    - stage: tests
      script: pytest app/tests
      script: pytest web/tests