version: '3.4'

x-defaults: &defaults
  restart: unless-stopped
  image: sentry:9.0-onbuild
  depends_on:
    - redis
    - opp-database
    - memcached
    - smtp
  env_file: .env
  environment:
    SENTRY_MEMCACHED_HOST: memcached
    SENTRY_REDIS_HOST: redis
    SENTRY_POSTGRES_HOST: opp-database
    SENTRY_EMAIL_HOST: smtp
  volumes:
    - sentry-data:/var/lib/sentry/files


services:
    smtp:
        restart: unless-stopped
        image: tianon/exim4

    memcached:
        restart: unless-stopped
        image: memcached:1.5-alpine

    opp-database:
        image: postgres
        restart: always
        environment:
            - POSTGRES_PASSWORD=mypass
            - POSTGRES_USER=perry
        ports:
            - 5433:5432
        volumes:
            - opportunity-postgres:/var/lib/postgresql/data
    opp-app:
        build: ./app
        restart: always
        volumes:
            - /c/Users/perry/WSL/Workspace/for_fun/opportunity/app:/usr/src/app/app
        ports:
            - 5001:80
        depends_on:
            - opp-database
    redis:
        image: redis
        ports:
            - "6379:6379"
        command: redis-server --appendonly yes
    
    sentry-web:
        <<: *defaults
        ports:
          - '9000:9000'

    sentry-cron:
        <<: *defaults
        command: run cron

    sentry-worker:
        <<: *defaults
        command: run worker

    opp-web:
        build: ./web
        restart: always
        volumes:
            - /c/Users/perry/WSL/Workspace/for_fun/opportunity/web:/usr/src/app/web
        ports:
            - 5002:81
        depends_on:
            - opp-database
            - opp-app
            - sentry-web
            - sentry-cron
            - sentry-worker
    opp-swagger:
        image: swaggerapi/swagger-ui
        restart: always
        volumes:
            - /c/Users/perry/WSL/Workspace/for_fun/opportunity/app:/usr/src/app/app
        environment:
            - SWAGGER_JSON=/usr/src/app/app/swagger.json
        ports:
            - 5004:8080
        depends_on:
            - opp-app
    opp-docs:
        build: ./
        restart: always
        environment:
            - NGINX_PORT=80
        ports:
            - 5005:80
        depends_on:
            - opp-app
            - opp-web

volumes:
    sentry-data:
        external: true
    opportunity-postgres:
        external: true